In [2]:
import pandas as pd
import jieba.analyse
import jieba
# 有的环境配置下read_table出错，因此改用read_csv
raw2 = pd.read_csv("附件3_金庸-天龙八部txt精校版.txt",
                  names = ['txt'], sep ='aaa', encoding ="utf-8" ,engine='python')
def A(Astr):
    for i in Astr.split(' ')[0]:
        if i not in '一二三四五六七八九十' or len(Astr.split(' ')[0])>=4:
            return ''
        else:
            return Astr.split(' ')[0]
    
raw2['p']=raw2.txt.apply(A)
raw2_q=[]
qNum=0
for i in list(raw2['p']):
    if i!='':
        qNum+=1
    if qNum>=50:
        qNum=0
    raw2_q.append(qNum)
raw2['chap']=raw2_q

In [3]:
raw2

                                                     txt p   chap
0                                                书名：天龙八部        0
1                                                  作者：金庸        0
2      ----------------------------------------------...        0
3                                ☆本文由早安电子书网友分享，版权归原作者所有☆        0
4                                      ☆请勿用于商业行为，一切后果自负☆        0
...                                                  ... ..   ...
10963                            ☆本文由早安电子书网友分享，版权归原作者所有☆        0
10964                                  ☆请勿用于商业行为，一切后果自负☆        0
10965                                            ☆早安电子书☆        0
10966                             ☆http://www.zadzs.com☆        0
10967  ----------------------------------------------...        0

[10968 rows x 3 columns]